console.log('hello world')
console.log('git branch develepment')
console.log('third commit')
console.log('forth commit on master')
console.log('fifth commit on development')
console.log('sixth commit on master')
console.log('seventh on development')
console.log('nineth on development')
console.log('eighth commit on master')
console.log('added manualy on gitHub')
console.log('new')
